### ISSUE TITLE
Challenges with all() and retrieve() functions, and outdated documentation

### ISSUE THREAD

**Issue by kouetcha** [fedapay/fedapay-php#10]
Hey team, it seems like the functions all() and retrieve() aren't functioning properly, and to add to the challenge, it looks like the documentation might be a bit outdated. Let's put our heads together and figure out the best way to troubleshoot and resolve these issues. We've got this! 💪
[Invoquer /v1/transactions est obsolète. Utiliser plutôt /v1/transactions/search.]

**Comment by brexis** [comment]
all method has been replaced by search and will be removed in the next release. Can you please describe the issue that you have with the retrieve method?
