### ISSUE TITLE
Retrieve customer by email or phone

### ISSUE THREAD

**Issue by nioperas06** [fedapay/fedapay-php#4]
@fabricethilaw https://docs.fedapay.com/development/api#operation/retrieve

**Comment by brexis** [comment]
Hi Junior.

Back from almost one year now, but I'm happy to say, there is a solution for this in `fedapay-php`.
To filter your resources, you need to call the `all` api operation with a `filters` param.
Filter param has:
* `compare` to do a operand comparison
* `order` to order the resources
* `includes` to filter nested resources

There is also `include` param witch returns nested resources within the result.
```
$customers = Customer::all([
    'filters' => [
      'compare' => [
        'email' => [
          'op' => '=',
          'value' => 'john@example.com'
        ]
      ],
      'order' => [
        'id' => 'DESC'
      ],
      'includes' => [
        'phone_number' => ['number' => '66000001']
       ]
    ],
    'include' => 'phone_number'
  ]);
  echo var_dump($customers);
```
For example to search for a customer by email, you will do:
```
$customers = Customer::all([
    'filters' => [
      'compare' => [
        'email' => [
          'op' => '=',
          'value' => 'john@example.com'
        ]
      ]
    ]
  ]);
  echo var_dump($customers);
```
For example to search for a customer by phone number, you will do:
```
$customers = Customer::all([
    'filters' => [
      'includes' => [
        'phone_number' => ['number' => '66000001']
       ]
    ],
    'include' => 'phone_number'
  ]);
  echo var_dump($customers);
```
Happy coding...
With ❤️ by FedaPay team.
