### ISSUE TITLE
Upgrade minimal PHP required version

### ISSUE THREAD

**Issue by adeys** [fedapay/fedapay-php#7]
Hi there,
With the PHP actively supported minimal version being 8.0 (7.4 will reach end of life next month: [https://www.php.net/supported-versions.php](https://www.php.net/supported-versions.php)), what about upgrading the php required version to >= 8.0 (or at least ^7.4 | >= 8.0) in composer.json file ?

**Comment by brexis** [comment]
Please check #9 !
